name: QQ邮箱自动发送

on:
  schedule:
    # 每周一、三、五的北京时间上午10点（UTC 02:00）执行
    - cron: '48 16 * * *'
  # 允许手动执行
  workflow_dispatch:

jobs:

  send-email:

    runs-on: ubuntu-latest

    steps:

      # 拉取项目代码
      - name: 拉取代码
        uses: actions/checkout@v4

      # 安装 Java 21
      - name: 设置 Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # 执行 Spring Boot
      - name: 发送邮件
        run: mvn -q spring-boot:run
        env:
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          MAIL_TO: ${{ secrets.MAIL_TO }}
